### ISSUE TITLE
[Documentation] Could it be clarified in the main README, or a linked-in document to the main README, whether boing would also work with libui as such, or just with libui-ng? E. g. a bit context for how it started would be nice.

### ISSUE THREAD

**Issue by rubyFeedback** [norepimorphism/boing#1]
Topic has the request, thank you.

(For simplicity I copy/paste it again here):

[Documentation] Could it be clarified in the main README, or a linked-in document to the main README, whether boing would also work with libui as such, or just with libui-ng? E. g. a bit context for how it started would be nice.

**Comment by norepimorphism** [comment]
Thanks for the issue!

I actually haven't tried *boing* with the original *libui* yet&mdash;I assumed their paths diverged (or will diverge) enough to make it tedious to support both. However, I will look into this. If it turns out that *libui-ng* is essentially a backwards-compatible update of *libui*, then I see no reason not to support it. If so, this will require changes in the sister crate *libui-ng-sys* as well.

For the time being, I will add a comment to the README that *boing*, in its current state, is only compatible with *libui-ng* due to *libui-ng-sys* not (yet?) supporting the original.
